version: '3'

x-common: &common
  restart: unless-stopped
  logging:
    options:
      max-size: "50m"
  networks:
      app_network: {}


services:
  database:
    <<: *common
    image: postgres:latest
    container_name: database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_title
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    <<: *common
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    command: /start
    depends_on:
      - database
      - cache
    environment:
      ENVIRONMENT: dev
      DB_USER: db_user
      DB_PASSWORD: db_password
      DB_TITLE: db_title
      DB_HOST: database
      DB_PORT: 5432
      REDIS_HOST: cache
      REDIS_PORT: 6379

  cache:
    <<: *common
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"

  nginx:
    <<: *common
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data:

networks:
  app_network:
