version: '3'

x-common: &common
  restart: unless-stopped
  logging:
    options:
      max-size: "50m"


services:
  database:
    <<: *common
    image: postgres:latest
    container_name: database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: betting_password
      POSTGRES_USER: betting_user
      POSTGRES_DB: betting
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    <<: *common
    build: .
    container_name: backend
    command: /unittest
    depends_on:
      - database
      - cache
    environment:
      ENVIRONMENT: dev
      DB_TITLE: betting
      DB_USER: betting_user
      DB_PASSWORD: betting_password
      DB_HOST: database
      DB_PORT: 5432
    ports:
      - "5000:5000"

volumes:
  db_data:
